spring:
  datasource:
    url: jdbc:mysql://localhost:3306/armbeautysalons?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  liquibase:
    change-log: classpath:/db/changelog/migration.xml

server:
  port: 3306
