spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: armbeautysalons@gmail.com
    password: ryjzhmilczksmdto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      fail-on-empty-beans:  false

server:
  port: 8081




